
/*

 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JFrame;
import Entidades.Usuario;

public class FrmPrincipal extends javax.swing.JFrame {

    private Usuario usuarioActivo; // Usuario autenticado

    // Constructor que recibe el usuario desde FrmLogin
    public FrmPrincipal(Usuario usuarioActivo) {
        initComponents();
        this.usuarioActivo = usuarioActivo;

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);

        // Mostrar datos del usuario en la barra de estado
        lblUsuario.setText("Usuario: " + usuarioActivo.getNombreUsuario());
        lblRol.setText("Rol: " + obtenerNombreRol(usuarioActivo.getIdRol()));
        lblFechaHora.setText("Fecha/Hora: " + obtenerFechaHoraActual());

        // Controlar accesos según rol
        controlarAcceso(usuarioActivo.getIdRol());
    }

    // Constructor vacío (solo para pruebas)
    public FrmPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);

        lblUsuario.setText("Usuario: -");
        lblRol.setText("Rol: -");
        lblFechaHora.setText("Fecha/Hora: " + obtenerFechaHoraActual());
    }

    // Método auxiliar para actualizar usuario activo
    public void setUsuarioActivo(Usuario u) {
        this.usuarioActivo = u;
        lblUsuario.setText("Usuario: " + u.getNombreUsuario());
        lblRol.setText("Rol: " + obtenerNombreRol(u.getIdRol()));
        controlarAcceso(u.getIdRol());
    }

    private String obtenerFechaHoraActual() {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
        return sdf.format(new java.util.Date());
    }

    private String obtenerNombreRol(int idRol) {
        switch (idRol) {
            case 1: return "Administrador";
            case 2: return "Vendedor";
            default: return "Usuario";
        }
    }

    private void controlarAcceso(int idRol) {
        boolean esVendedor = (idRol == 2);
        mnuUsuarios.setEnabled(!esVendedor);
        mnuRoles.setEnabled(!esVendedor);
        mnuCompras.setEnabled(!esVendedor);
    }

    private void abrirFormulario(javax.swing.JInternalFrame frame) {
        escritorio.add(frame);   // escritorio es tu JDesktopPane
        frame.setVisible(true);
    }

    // Acción del menú Ventas
   // private void mnuVentasActionPerformed(java.awt.event.ActionEvent evt) {
     //   // Pasar el id_usuario al FrmVenta
       // FrmVenta frmVenta = new FrmVenta(usuarioActivo.getIdUsuario());
        //abrirFormulario(frmVenta);
    //}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        panelEstado = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenuItem();
        mnuRoles = new javax.swing.JMenuItem();
        mnuCompras = new javax.swing.JMenu();
        mnuVentas = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas – Menú Principal");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        panelEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblUsuario.setText("jLabel2");
        panelEstado.add(lblUsuario);

        lblRol.setText("jLabel1");
        panelEstado.add(lblRol);

        lblFechaHora.setText("jLabel1");
        panelEstado.add(lblFechaHora);

        jMenu1.setText("Archivo");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenimiento");

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuClientes);

        mnuProveedores.setText("Proveedores");
        mnuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProveedoresActionPerformed(evt);
            }
        });
        jMenu2.add(mnuProveedores);

        mnuProductos.setText("Productos");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuProductos);

        jMenuItem4.setText("Categorias");
        jMenu2.add(jMenuItem4);

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuUsuarios);

        mnuRoles.setText("Roles");
        jMenu2.add(mnuRoles);

        jMenuBar1.add(jMenu2);

        mnuCompras.setText("Operaciones");

        mnuVentas.setText("Ventas");
        mnuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasActionPerformed(evt);
            }
        });
        mnuCompras.add(mnuVentas);

        jMenuItem8.setText("Compras");
        mnuCompras.add(jMenuItem8);

        jMenuBar1.add(mnuCompras);

        jMenu6.setText("Reportes");

        jMenuItem9.setText("Inventario");
        jMenu6.add(jMenuItem9);

        jMenuItem10.setText("Ventas por fecha");
        jMenu6.add(jMenuItem10);

        jMenuItem11.setText("Compras por proveedor");
        jMenu6.add(jMenuItem11);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(escritorio)
                        .addContainerGap())
                    .addComponent(panelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
       abrirFormulario(new FrmClientes()); // TODO add your handling code here:
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProveedoresActionPerformed
       abrirFormulario(new FrmProveedores());
    }//GEN-LAST:event_mnuProveedoresActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
       javax.swing.JInternalFrame activo = escritorio.getSelectedFrame();
    if (activo != null) {
        activo.dispose(); // Cierra el formulario interno
    } 
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentasActionPerformed
 FrmVenta frmVenta = new FrmVenta(usuarioActivo.getIdUsuario());
        abrirFormulario(frmVenta);
    }//GEN-LAST:event_mnuVentasActionPerformed

    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
        abrirFormulario(new FrmProductos());
      
    }//GEN-LAST:event_mnuProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel lblFechaHora;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenu mnuCompras;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuProveedores;
    private javax.swing.JMenuItem mnuRoles;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuUsuarios;
    private javax.swing.JMenuItem mnuVentas;
    private javax.swing.JPanel panelEstado;
    // End of variables declaration//GEN-END:variables
}
