/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Entidades.Venta;
import Entidades.DetalleVenta;
import Entidades.Producto;
import Datos.VentaDAO;
import Datos.ProductoDAO;
import Datos.ClienteDAO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.*;
/**
 *
 * @author macbook
 */
public class FrmVenta extends javax.swing.JInternalFrame {

    private VentaDAO ventaDAO = new VentaDAO();
    private ProductoDAO productoDAO = new ProductoDAO();
    private ClienteDAO clienteDAO = new ClienteDAO();
    
    
    private DefaultTableModel modeloDetalle;
    private Map<Integer, String> clientesMapa = new LinkedHashMap<>();
    
    public FrmVenta() {
        initComponents();
        setTitle("Registro de Venta");
        configurarTabla();
        cargarClientes();
        mostrarFecha();
        actualizarTotales();
        txtNombreProducto.setEditable(false); // no editable
        
    }

    private void configurarTabla() {
        modeloDetalle = new DefaultTableModel(
            new Object[]{"ID Producto", "Nombre", "Cantidad", "Precio", "Importe"}, 0
        ) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
            @Override public Class<?> getColumnClass(int c) {
                return switch (c) {
                    case 0 -> Integer.class;
                    case 2 -> Integer.class;
                    case 3,4 -> Double.class;
                    default -> String.class;
                };
            }
        };
        tblDetalle.setModel(modeloDetalle);
    }
    
    
   private void cargarClientes() {
       clientesMapa = clienteDAO.listarMapa();
             cboCliente.removeAllItems();
    for (String nombre : clientesMapa.values()) {
        cboCliente.addItem(nombre);
    }
    }
    
    private void mostrarFecha() {
        String f = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date());
        lblFecha.setText("Fecha: " + f);
    }
    
    private int getIdClienteSeleccionado() {
        int index = cboCliente.getSelectedIndex();
        if (index < 0) return 0;
        int i = 0;
        for (Map.Entry<Integer, String> e : clientesMapa.entrySet()) {
            if (i == index) return e.getKey();
            i++;
        }
        return 0;
    }
    
    private void actualizarTotales() {
        double subtotal = 0.0;
        for (int i = 0; i < modeloDetalle.getRowCount(); i++) {
            subtotal += (double) modeloDetalle.getValueAt(i, 4);
        }
        double igv = subtotal * 0.18;
        double total = subtotal + igv;
        lblSubtotal.setText(String.format("Subtotal: %.2f", subtotal));
        lblIGV.setText(String.format("IGV: %.2f", igv));
        lblTotal.setText(String.format("Total: %.2f", total));
}
    
    private double getSubtotal() {
    double subtotal = 0.0;
    for (int i = 0; i < modeloDetalle.getRowCount(); i++) {
        subtotal += (double) modeloDetalle.getValueAt(i, 4); // columna "Importe"
    }
    return subtotal;
}

private double getIGV(double subtotal) {
    return subtotal * 0.18;
}

        
        private void limpiarLineaProducto() {
        txtIdProducto.setText("");
        txtNombreProducto.setText("");
        txtPrecio.setText("");
        txtStockDisp.setText("");
        txtCantidad.setText("");
        }
        private void limpiarVenta() {
        modeloDetalle.setRowCount(0);
        actualizarTotales();
        limpiarLineaProducto();
        if (cboCliente.getItemCount() > 0) cboCliente.setSelectedIndex(0);
        mostrarFecha();
    }
    private int idUsuario;

public FrmVenta(int idUsuario) {
    initComponents();
    this.idUsuario = idUsuario;
    setTitle("Registro de Venta");
    configurarTabla();
    cargarClientes();
    mostrarFecha();
    actualizarTotales();
    txtNombreProducto.setEditable(false);
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboCliente = new javax.swing.JComboBox<>();
        lblFecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStockDisp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        lblSubtotal = new javax.swing.JLabel();
        lblIGV = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnGuardarVenta = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnQuitarItem = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();

        jLabel1.setText("Cliente");

        cboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblFecha.setText("jLabel2");

        jLabel2.setText("Id producto");

        txtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre producto");

        jLabel4.setText("Precio");

        jLabel5.setText("Stock disponible");

        jLabel6.setText("Cantidad");

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblSubtotal.setText("jLabel7");

        lblIGV.setText("jLabel7");

        lblTotal.setText("jLabel7");

        btnGuardarVenta.setText("Registrar venta");
        btnGuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVentaActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnQuitarItem.setText("Quitar");
        btnQuitarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarItemActionPerformed(evt);
            }
        });

        btnBuscarProducto.setText("Buscar producto");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStockDisp)
                            .addComponent(jLabel5))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarVenta)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarItem)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(lblIGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFecha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStockDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBuscarProducto))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtotal)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIGV)
                    .addComponent(btnGuardarVenta)
                    .addComponent(btnNuevo)
                    .addComponent(btnQuitarItem)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
  if (txtIdProducto.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un ID de producto.");
        return;
    }

    try {
        int idProducto = Integer.parseInt(txtIdProducto.getText().trim());
        Producto p = productoDAO.buscarPorId(idProducto); // usa siempre el mismo método

        if (p != null) {
            txtNombreProducto.setText(p.getNombre());
            txtPrecio.setText(String.valueOf(p.getPrecio()));
            txtStockDisp.setText(String.valueOf(p.getStock())); // usa txtStockDisp
            
        } else {
            JOptionPane.showMessageDialog(this, "Producto no encontrado");
            limpiarLineaProducto();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese un ID válido");
    }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    if (txtIdProducto.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Seleccione un producto.");
        return;
    }
    if (txtCantidad.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese cantidad.");
        return;
    }
    try {
        int idProd = Integer.parseInt(txtIdProducto.getText().trim());
        String nombre = txtNombreProducto.getText().trim();
        int cant = Integer.parseInt(txtCantidad.getText().trim());
        double precio = Double.parseDouble(txtPrecio.getText().trim());
        int stock = Integer.parseInt(txtStockDisp.getText().trim());

        if (cant <= 0 || cant > stock) {
            JOptionPane.showMessageDialog(this, "Cantidad inválida o supera stock.");
            return;
        }

        double importe = cant * precio;
        modeloDetalle.addRow(new Object[]{idProd, nombre, cant, precio, importe});
        actualizarTotales();
        limpiarLineaProducto();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error en datos del producto.");
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarItemActionPerformed
     int row = tblDetalle.getSelectedRow();
    if (row >= 0) {
        modeloDetalle.removeRow(row);
        actualizarTotales();
    }
    }//GEN-LAST:event_btnQuitarItemActionPerformed

    private void btnGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVentaActionPerformed
    try {
         // 1. Cabecera
        Venta venta = new Venta();
        venta.setIdCliente(getIdClienteSeleccionado()); 
        venta.setIdUsuario(idUsuario); // transmitido desde login

        double subtotal = getSubtotal();
        double igv = getIGV(subtotal);
        double total = subtotal + igv;

        venta.setSubtotal(subtotal);
        venta.setIgv(igv);
        venta.setTotal(total);

        // 2. Detalles
        List<DetalleVenta> listaDetalles = new ArrayList<>();
        for (int i = 0; i < tblDetalle.getRowCount(); i++) {
            DetalleVenta d = new DetalleVenta();
            d.setIdProducto((int) tblDetalle.getValueAt(i, 0));
            d.setCantidad((int) tblDetalle.getValueAt(i, 2));
            d.setPrecioUnitario((double) tblDetalle.getValueAt(i, 3));
            d.setSubtotal(d.getCantidad() * d.getPrecioUnitario());
            listaDetalles.add(d);
        }

        // 3. Guardar
        boolean ok = ventaDAO.registrarVentaConDetalles(venta, listaDetalles);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Venta registrada correctamente");
            limpiarVenta();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar la venta");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    System.out.println("ID USUARIO ENVIADO: " + idUsuario);

    }//GEN-LAST:event_btnGuardarVentaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       limpiarVenta();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoActionPerformed
     if (txtIdProducto.getText().trim().isEmpty()) return;

    try {
        int idProd = Integer.parseInt(txtIdProducto.getText().trim());
        Producto p = productoDAO.buscarPorId(idProd); //  usa el mismo método

        if (p != null) {
            txtNombreProducto.setText(p.getNombre());
            txtPrecio.setText(String.valueOf(p.getPrecio()));
            txtStockDisp.setText(String.valueOf(p.getStock()));
           
        } else {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
            limpiarLineaProducto();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido.");
    }
    }//GEN-LAST:event_txtIdProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnGuardarVenta;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnQuitarItem;
    private javax.swing.JComboBox<String> cboCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIGV;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStockDisp;
    // End of variables declaration//GEN-END:variables
}